=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::AccountUsersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountUsersApi' do
  before do
    # run before each test
    @api_instance = Cfchat::AccountUsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountUsersApi' do
    it 'should create an instance of AccountUsersApi' do
      expect(@api_instance).to be_instance_of(Cfchat::AccountUsersApi)
    end
  end

  # unit tests for create_an_account_user
  # Create an Account User
  # Create an Account User
  # @param account_id The numeric ID of the account
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'create_an_account_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_an_account_user
  # Delete an Account User
  # Delete an Account User
  # @param account_id The numeric ID of the account
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_an_account_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_account_users
  # List all Account Users
  # List all account users
  # @param account_id The numeric ID of the account
  # @param [Hash] opts the optional parameters
  # @return [Array<ListAllAccountUsers200ResponseInner>]
  describe 'list_all_account_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
