=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::AccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @api_instance = Cfchat::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@api_instance).to be_instance_of(Cfchat::AccountsApi)
    end
  end

  # unit tests for create_an_account
  # Create an Account
  # Create an Account
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [PlatformAccount]
  describe 'create_an_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_an_account
  # Delete an Account
  # Delete an Account
  # @param account_id The numeric ID of the account
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_an_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_details_of_an_account
  # Get an account details
  # Get the details of an account
  # @param account_id The numeric ID of the account
  # @param [Hash] opts the optional parameters
  # @return [PlatformAccount]
  describe 'get_details_of_an_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_an_account
  # Update an account
  # Update an account&#39;s attributes
  # @param account_id The numeric ID of the account
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [PlatformAccount]
  describe 'update_an_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
