=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::AgentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AgentsApi' do
  before do
    # run before each test
    @api_instance = Cfchat::AgentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AgentsApi' do
    it 'should create an instance of AgentsApi' do
      expect(@api_instance).to be_instance_of(Cfchat::AgentsApi)
    end
  end

  # unit tests for add_new_agent_to_account
  # Add a New Agent
  # Add a new Agent to Account
  # @param account_id The numeric ID of the account
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Agent]
  describe 'add_new_agent_to_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_agent_from_account
  # Remove an Agent from Account
  # Remove an Agent from Account
  # @param account_id The numeric ID of the account
  # @param id The ID of the agent to be deleted
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_agent_from_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_account_agents
  # List Agents in Account
  # Get Details of Agents in an Account
  # @param account_id The numeric ID of the account
  # @param [Hash] opts the optional parameters
  # @return [Array<Agent>]
  describe 'get_account_agents test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_agent_in_account
  # Update Agent in Account
  # Update an Agent in Account
  # @param account_id The numeric ID of the account
  # @param id The ID of the agent to be updated.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Agent]
  describe 'update_agent_in_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
