=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::CannedResponsesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CannedResponsesApi' do
  before do
    # run before each test
    @api_instance = Cfchat::CannedResponsesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CannedResponsesApi' do
    it 'should create an instance of CannedResponsesApi' do
      expect(@api_instance).to be_instance_of(Cfchat::CannedResponsesApi)
    end
  end

  # unit tests for add_new_canned_response_to_account
  # Add a New Canned Response
  # Add a new Canned Response to Account
  # @param account_id The numeric ID of the account
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CannedResponse]
  describe 'add_new_canned_response_to_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_canned_response_from_account
  # Remove a Canned Response from Account
  # Remove a Canned Response from Account
  # @param account_id The numeric ID of the account
  # @param id The ID of the canned response to be deleted
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_canned_response_from_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_account_canned_response
  # List all Canned Responses in an Account
  # Get Details of Canned Responses in an Account
  # @param account_id The numeric ID of the account
  # @param [Hash] opts the optional parameters
  # @return [Array<CannedResponse>]
  describe 'get_account_canned_response test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
