=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::CannedResponseApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CannedResponseApi' do
  before do
    # run before each test
    @api_instance = Cfchat::CannedResponseApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CannedResponseApi' do
    it 'should create an instance of CannedResponseApi' do
      expect(@api_instance).to be_instance_of(Cfchat::CannedResponseApi)
    end
  end

  # unit tests for update_canned_response_in_account
  # Update Canned Response in Account
  # Update a Canned Response in Account
  # @param account_id The numeric ID of the account
  # @param id The ID of the canned response to be updated.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CannedResponse]
  describe 'update_canned_response_in_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
