=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::ContactsAPIApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContactsAPIApi' do
  before do
    # run before each test
    @api_instance = Cfchat::ContactsAPIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactsAPIApi' do
    it 'should create an instance of ContactsAPIApi' do
      expect(@api_instance).to be_instance_of(Cfchat::ContactsAPIApi)
    end
  end

  # unit tests for create_a_contact
  # Create a contact
  # Create a contact
  # @param inbox_identifier The identifier obtained from API inbox channel
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [PublicContact]
  describe 'create_a_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_details_of_a_contact
  # Get a contact
  # Get the details of a contact
  # @param inbox_identifier The identifier obtained from API inbox channel
  # @param contact_identifier The source id of contact obtained on contact create
  # @param [Hash] opts the optional parameters
  # @return [PublicContact]
  describe 'get_details_of_a_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_a_contact
  # Update a contact
  # Update a contact&#39;s attributes
  # @param inbox_identifier The identifier obtained from API inbox channel
  # @param contact_identifier The source id of contact obtained on contact create
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [PublicContact]
  describe 'update_a_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
