=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::ContactApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContactApi' do
  before do
    # run before each test
    @api_instance = Cfchat::ContactApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactApi' do
    it 'should create an instance of ContactApi' do
      expect(@api_instance).to be_instance_of(Cfchat::ContactApi)
    end
  end

  # unit tests for contact_inbox_creation
  # Create contact inbox
  # Create a contact inbox record for an inbox
  # @param account_id The numeric ID of the account
  # @param id ID of the contact
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [ContactInboxes]
  describe 'contact_inbox_creation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for contactable_inboxes_get
  # Get Contactable Inboxes
  # Get List of contactable Inboxes
  # @param account_id The numeric ID of the account
  # @param id ID of the contact
  # @param [Hash] opts the optional parameters
  # @return [ContactableInboxes]
  describe 'contactable_inboxes_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
