=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::ConversationsAPIApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConversationsAPIApi' do
  before do
    # run before each test
    @api_instance = Cfchat::ConversationsAPIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConversationsAPIApi' do
    it 'should create an instance of ConversationsAPIApi' do
      expect(@api_instance).to be_instance_of(Cfchat::ConversationsAPIApi)
    end
  end

  # unit tests for create_a_conversation
  # Create a conversation
  # Create a conversation
  # @param inbox_identifier The identifier obtained from API inbox channel
  # @param contact_identifier The source id of contact obtained on contact create
  # @param [Hash] opts the optional parameters
  # @return [PublicConversation]
  describe 'create_a_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_contact_conversations
  # List all conversations
  # List all conversations for the contact
  # @param inbox_identifier The identifier obtained from API inbox channel
  # @param contact_identifier The source id of contact obtained on contact create
  # @param [Hash] opts the optional parameters
  # @return [Array<PublicConversation>]
  describe 'list_all_contact_conversations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
