=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::ConversationLabelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConversationLabelsApi' do
  before do
    # run before each test
    @api_instance = Cfchat::ConversationLabelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConversationLabelsApi' do
    it 'should create an instance of ConversationLabelsApi' do
      expect(@api_instance).to be_instance_of(Cfchat::ConversationLabelsApi)
    end
  end

  # unit tests for conversation_add_labels
  # Add Labels
  # Add labels to a conversation. Note that this API would overwrite the existing list of labels associated to the conversation.
  # @param account_id The numeric ID of the account
  # @param conversation_id The numeric ID of the conversation
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [ConversationLabels]
  describe 'conversation_add_labels test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_labels_of_a_conversation
  # List Labels
  # Lists all the labels of a conversation
  # @param account_id The numeric ID of the account
  # @param conversation_id The numeric ID of the conversation
  # @param [Hash] opts the optional parameters
  # @return [ConversationLabels]
  describe 'list_all_labels_of_a_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
