=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::ConversationAssignmentApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConversationAssignmentApi' do
  before do
    # run before each test
    @api_instance = Cfchat::ConversationAssignmentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConversationAssignmentApi' do
    it 'should create an instance of ConversationAssignmentApi' do
      expect(@api_instance).to be_instance_of(Cfchat::ConversationAssignmentApi)
    end
  end

  # unit tests for assign_a_conversation
  # Assign Conversation
  # Assign a conversation to an agent or a team
  # @param account_id The numeric ID of the account
  # @param conversation_id The numeric ID of the conversation
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'assign_a_conversation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
