=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::CustomAttributesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomAttributesApi' do
  before do
    # run before each test
    @api_instance = Cfchat::CustomAttributesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomAttributesApi' do
    it 'should create an instance of CustomAttributesApi' do
      expect(@api_instance).to be_instance_of(Cfchat::CustomAttributesApi)
    end
  end

  # unit tests for add_new_custom_attribute_to_account
  # Add a new custom attribute
  # Add a new custom attribute to account
  # @param account_id The numeric ID of the account
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CustomAttribute]
  describe 'add_new_custom_attribute_to_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_custom_attribute_from_account
  # Remove a custom attribute from account
  # Remove a custom attribute from account
  # @param account_id The numeric ID of the account
  # @param id The ID of the custom attribute to be deleted
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_custom_attribute_from_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_account_custom_attribute
  # List all custom attributes in an account
  # Get details of custom attributes in an Account
  # @param account_id The numeric ID of the account
  # @param attribute_model conversation_attribute(0)/contact_attribute(1)
  # @param [Hash] opts the optional parameters
  # @return [Array<CustomAttribute>]
  describe 'get_account_custom_attribute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_details_of_a_single_custom_attribute
  # Get a custom attribute details
  # Get the details of a custom attribute in the account
  # @param account_id The numeric ID of the account
  # @param id The ID of the custom attribute to be updated.
  # @param [Hash] opts the optional parameters
  # @return [CustomAttribute]
  describe 'get_details_of_a_single_custom_attribute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_custom_attribute_in_account
  # Update custom attribute in Account
  # Update a custom attribute in account
  # @param account_id The numeric ID of the account
  # @param id The ID of the custom attribute to be updated.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CustomAttribute]
  describe 'update_custom_attribute_in_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
