=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::IntegrationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IntegrationsApi' do
  before do
    # run before each test
    @api_instance = Cfchat::IntegrationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IntegrationsApi' do
    it 'should create an instance of IntegrationsApi' do
      expect(@api_instance).to be_instance_of(Cfchat::IntegrationsApi)
    end
  end

  # unit tests for create_an_integration_hook
  # Create an integration hook
  # Create an integration hook
  # @param account_id The numeric ID of the account
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [IntegrationsHook]
  describe 'create_an_integration_hook test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_an_integration_hook
  # Delete an Integration Hook
  # Delete an Integration Hook
  # @param account_id The numeric ID of the account
  # @param hook_id The numeric ID of the integration hook
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_an_integration_hook test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_details_of_all_integrations
  # List all the Integrations
  # Get the details of all Integrations available for the account
  # @param account_id The numeric ID of the account
  # @param [Hash] opts the optional parameters
  # @return [Array<IntegrationsApp>]
  describe 'get_details_of_all_integrations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_an_integrations_hook
  # Update an Integration Hook
  # Update an Integration Hook
  # @param account_id The numeric ID of the account
  # @param hook_id The numeric ID of the integration hook
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [IntegrationsHook]
  describe 'update_an_integrations_hook test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
