=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::ReportsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReportsApi' do
  before do
    # run before each test
    @api_instance = Cfchat::ReportsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReportsApi' do
    it 'should create an instance of ReportsApi' do
      expect(@api_instance).to be_instance_of(Cfchat::ReportsApi)
    end
  end

  # unit tests for get_account_conversation_metrics
  # Account Conversation Metrics
  # Get conversation metrics for Account
  # @param account_id The numeric ID of the account
  # @param type Type of report
  # @param [Hash] opts the optional parameters
  # @return [GetAccountConversationMetrics200Response]
  describe 'get_account_conversation_metrics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_agent_conversation_metrics
  # Agent Conversation Metrics
  # Get conversation metrics for Agent
  # @param account_id The numeric ID of the account
  # @param type Type of report
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id The numeric ID of the user
  # @return [Array<AgentConversationMetrics>]
  describe 'get_agent_conversation_metrics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_conversation_statistics
  # Get Account reports
  # Get Account reports for a specific type, metric and date range
  # @param account_id The numeric ID of the account
  # @param metric The type of metric
  # @param type Type of report
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id The Id of specific object in case of agent/inbox/label
  # @option opts [String] :since The timestamp from where report should start.
  # @option opts [String] :_until The timestamp from where report should stop.
  # @return [Array<ListAllConversationStatistics200ResponseInner>]
  describe 'list_all_conversation_statistics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_conversation_statistics_summary
  # Get Account reports summary
  # Get Account reports summary for a specific type and date range
  # @param account_id The numeric ID of the account
  # @param type Type of report
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id The Id of specific object in case of agent/inbox/label
  # @option opts [String] :since The timestamp from where report should start.
  # @option opts [String] :_until The timestamp from where report should stop.
  # @return [AccountSummary]
  describe 'list_all_conversation_statistics_summary test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
