=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::TeamsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TeamsApi' do
  before do
    # run before each test
    @api_instance = Cfchat::TeamsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TeamsApi' do
    it 'should create an instance of TeamsApi' do
      expect(@api_instance).to be_instance_of(Cfchat::TeamsApi)
    end
  end

  # unit tests for add_new_agent_to_team
  # Add a New Agent
  # Add a new Agent to Team
  # @param account_id The numeric ID of the account
  # @param team_id The ID of the team to be updated
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Array<Agent>]
  describe 'add_new_agent_to_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_a_team
  # Create a team
  # Create a team in the account
  # @param account_id The numeric ID of the account
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Team]
  describe 'create_a_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_a_team
  # Delete a team
  # Delete a team from the account
  # @param account_id The numeric ID of the account
  # @param team_id The ID of the team to be updated
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_a_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_agent_in_team
  # Remove an Agent from Team
  # Remove an Agent from Team
  # @param account_id The numeric ID of the account
  # @param team_id The ID of the team to be updated
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_agent_in_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_details_of_a_single_team
  # Get a team details
  # Get the details of a team in the account
  # @param account_id The numeric ID of the account
  # @param team_id The ID of the team to be updated
  # @param [Hash] opts the optional parameters
  # @return [Team]
  describe 'get_details_of_a_single_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_team_members
  # List Agents in Team
  # Get Details of Agents in an Team
  # @param account_id The numeric ID of the account
  # @param team_id The ID of the team to be updated
  # @param [Hash] opts the optional parameters
  # @return [Array<Agent>]
  describe 'get_team_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_teams
  # List all teams
  # List all teams available in the current account
  # @param account_id The numeric ID of the account
  # @param [Hash] opts the optional parameters
  # @return [Array<Team>]
  describe 'list_all_teams test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_a_team
  # Update a team
  # Update a team&#39;s attributes
  # @param account_id The numeric ID of the account
  # @param team_id The ID of the team to be updated
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Team]
  describe 'update_a_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_agents_in_team
  # Update Agents in Team
  # All agents except the one passed in params will be removed
  # @param account_id The numeric ID of the account
  # @param team_id The ID of the team to be updated
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Array<Agent>]
  describe 'update_agents_in_team test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
