=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::UsersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @api_instance = Cfchat::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@api_instance).to be_instance_of(Cfchat::UsersApi)
    end
  end

  # unit tests for create_a_user
  # Create a User
  # Create a User
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'create_a_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_a_user
  # Delete a User
  # Delete a User
  # @param id The numeric ID of the user on the platform
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_a_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_details_of_a_user
  # Get an user details
  # Get the details of an user
  # @param id The numeric ID of the user on the platform
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'get_details_of_a_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sso_url_of_a_user
  # Get User SSO Link
  # Get the sso link of a user
  # @param id The numeric ID of the user on the platform
  # @param [Hash] opts the optional parameters
  # @return [GetSsoUrlOfAUser200Response]
  describe 'get_sso_url_of_a_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_a_user
  # Update a user
  # Update a user&#39;s attributes
  # @param id The numeric ID of the user on the platform
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'update_a_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
