=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Cfchat::WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @api_instance = Cfchat::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@api_instance).to be_instance_of(Cfchat::WebhooksApi)
    end
  end

  # unit tests for create_a_webhook
  # Add a webhook
  # Add a webhook subscription to the account
  # @param account_id The numeric ID of the account
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Webhook]
  describe 'create_a_webhook test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_a_webhook
  # Delete a webhook
  # Delete a webhook from the account
  # @param account_id The numeric ID of the account
  # @param webhook_id The numeric ID of the webhook
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_a_webhook test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_all_webhooks
  # List all webhooks
  # List all webhooks in the account
  # @param account_id The numeric ID of the account
  # @param [Hash] opts the optional parameters
  # @return [Array<Webhook>]
  describe 'list_all_webhooks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_a_webhook
  # Update a webhook object
  # Update a webhook object in the account
  # @param account_id The numeric ID of the account
  # @param webhook_id The numeric ID of the webhook
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Webhook]
  describe 'update_a_webhook test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
