=begin
#CF Chat

#This is the API documentation for CF Chat server.

The version of the OpenAPI document: 1.0.0
Contact: support@clickfunnels.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Cfchat::UpdateAgentBotRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Cfchat::UpdateAgentBotRequest do
  let(:instance) { Cfchat::UpdateAgentBotRequest.new }

  describe 'test an instance of UpdateAgentBotRequest' do
    it 'should create an instance of UpdateAgentBotRequest' do
      expect(instance).to be_instance_of(Cfchat::UpdateAgentBotRequest)
    end
  end
  describe 'test attribute "agent_bot"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
